title: ğŸ³ï¸â€âš§ï¸ğŸ³ï¸â€ğŸŒˆğŸš©ğŸ‡µğŸ‡¸ğŸ—âœ¨ï¸ğŸ‘©â€â¤ï¸â€ğŸ‘©
description: ì´ê²ƒì €ê²ƒ í•˜ëŠ” í€´ì–´ê³µì£¼ì˜ ì‚¬ì´íŠ¸
url: 6k2ldk.github.io
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
